### ISSUE TITLE
Confusing 'getSheet' method

### ISSUE THREAD

**Issue by tmlbl** [smartsheet-platform/smartsheet-javascript-sdk#49]
Calling the following method:
```javascript
client.sheets.getSheet({ sheetId: id })
```
Expected behavior: client calls API endpoint at `/sheets/:id`
Actual behavior: `getSheet` is an alias for `listSheets`, which does not serve the same purpose.

**Comment by cameronbowie** [comment]
The `getSheet` endpoint code is confusing; however, it does function as described in the API docs (http://smartsheet-platform.github.io/api-docs/?javascript#get-sheet). Rather than specifying `sheetId`, you need to specify `id`:
```
client.sheets.getSheet({ id: 123123123123 });
```
If you're curious about how it works, check out the `buildUrl` method in `lib/utils/httpRequestor.js`.
